version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: digital_library
      POSTGRES_USER: dl_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
